status: "ready"
preview: "@preview-no-padding"
variants:
    - name: "default"
      label: "Header base"
    - name: "id-menu"
      label: "Header w/ user ID (simple log out)"
      notes: |
        # Identity Menu
    - name: "main-nav"
      label: "Header w/ main navigation"
      notes: |
        # Main navigation
    - name: "persistent-drawer"
      label: "Header w/ persistent desktop drawer"
      notes: |
        # Desktop drawer
    - name: "light-background"
      label: "Header w/ light background"
      preview: "@preview-gray-stage"
      notes: |
        # Light background variant
    - name: "skip-link"
      label: "Header skip link example"
      notes: |
        # Skip navigation link