title: "Header"
status: "ready"
preview: "@preview-no-padding"
context:
    home: "#0"
    applicationTitle: "Application Title"
variants:
    - name: "id module"
      context:
          navigation: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          id: "mobile-drawer"
    - name: "id module advanced"
      context:
          navigation: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          dropdown: "true"
          userFunctions:
            - link: "#"
              text: "Account settings"
            - link: "#"
              text: "Admin task one"
            - link: "#"
              text: "Admin task two"
          id: "identity-module"
    - name: "navigation"
      context:
          navigation: "true"
          main: "true"
          navItems:
            - link: "#"
              text: "Nav one"
            - text: "Nav two"
              id: "1"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
            - link: "#"
              text: "Nav three"
            - text: "Nav four"
              id: "2"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
          id: "navigation"
    - name: "navigation identity"
      context:
          navigation: "true"
          main: "true"
          identityModule: "true"
          user:
            initials: "rs"
            username: "rswanson"
          dropdown: "true"
          userFunctions:
            - link: "#"
              text: "Account settings"
            - link: "#"
              text: "Admin task one"
            - link: "#"
              text: "Admin task two"
          navItems:
            - link: "#"
              text: "Nav one"
            - text: "Nav two"
              id: "1"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
            - link: "#"
              text: "Nav three"
            - text: "Nav four"
              id: "2"
              relatedLinks:
                - link: "#"
                  text: "Item one"
                - link: "#"
                  text: "Item two"
                - link: "#"
                  text: "Item three"
                - link: "#"
                  text: "Item four"
          id: "navigation-identity"
    - name: "default"
      label: "Header base"
    - name: "id-menu"
      label: "Header w/ user ID (simple log out)"
      notes: |
        # Identity Menu
    - name: "main-nav"
      label: "Header w/ main navigation"
      notes: |
        # Main navigation
    - name: "persistent-drawer"
      label: "Header w/ persistent desktop drawer"
      notes: |
        # Desktop drawer
    - name: "light-background"
      label: "Header w/ light background"
      preview: "@preview-gray-stage"
      notes: |
        # Light background variant
    - name: "skip-link"
      label: "Header skip link example"
      notes: |
        # Skip navigation link