title: Modals
preview: "@preview-modals"
variants:
    - name: "modal-dialog"
      label: "Modal - dialog"
      notes: >
        # Modal dialog
        
    - name: "information-modal"
      label: "Modal - information"
      notes: >
        # Information modal
    - name: "confirmation-modal"
      label: "Modal - confirmation"
      notes: >
        # Confirmation modal
    - name: "complex-modal"
      label: "Modal - complex"
      notes: >
        # Complex modal
