title: Quote
label: Quote
status: 'wip'
preview: '@preview-no-padding'
collated: true
context:
  utility_class: 'rvt-m-right-sm'
variants:
  - name: 'avatar-small'
    context:
      avatar: true
      attributes:
        text: 'SM'
        size: '--sm'
  - name: 'avatar-medium'
    context:
      avatar: true
      attributes:
        text: 'MD'
        size: '--md'
  - name: 'avatar-large'
    context:
      avatar: true
      attributes:
        text: 'LG'
        size: '--lg'
  - name: 'avatar-extra-large'
    context:
      avatar: true
      attributes:
        text: 'XL'
        size: '--xl'
