status: "alpha"
context:
    spacings:
        -   title: Extra extra small
            pixels: 4
            abbr: xxs
        -   title: Extra small
            pixels: 8
            abbr: xs
        -   title: Small
            pixels: 16
            abbr: sm
        -   title: Medium
            pixels: 24
            abbr: md
        -   title: Large
            pixels: 32
            abbr: lg
        -   title: Extra large
            pixels: 40
            abbr: xl
        -   title: Extra extra large
            pixels: 48
            abbr: xxl
