title: Input Group
status: "ready"
collated: true
context:
  id: "search"
  labelText: "Search"
  type: "button"
  content: "Search docs"
  modifier: "-secondary"
variants:
  - name: "prepend"
    context:
      prepend: true
      id: "segmented-prepend"
      labelText: "Add new"
      button: false
      type: "dropdown"
      title: "All stuff"