status: "alpha"
variants:
    - name: "default"
      label: "Standard Timeline"
    - name: "standard-dates"
      label: "Standard Timeline w/ Date Labels"
    - name: "centered"
      label: "Centered Timeline"
    - name: "centered-dates"
      label: "Centered Timeline w/ Date Labels"
    - name: "right-aligned"
      label: "Right-aligned Timeline"
    - name: "right-dates"
      label: "Right-aligned Timeline w/ Date Labels"