title: Alerts & errors
variants:
    - name: "default"
      label: "Page-level alerts"
    - name: "alert-lists"
      label: "Alert lists"
      notes: "Alert lists provide a way to group a set of errors together. For instance, when summarizing a list of errors on a long form."
    - name: "inline-errors"
      label: "Inline errors"
      notes: >
        # Inline alerts

        Inline alerts provide just-in-time information regarding the state of specific components, like invalid form fields

        ## When to use

        * To highlight fields with errors in forms

        * To provide users with form validation messaging


        ## Implementation

        Write helpful validation alert messages that explain the requirements for the form field(s).
        Show inline validation messages after the user submits the form. For longer form highlight each field with a validation error and summarize the errors at the top of the form using a page-level alert.

        ## Accessibility

        * a `role="alert"` attribute should be applied to the `<div class="alert-inline">`, and it should be given a **unique `id` attribute**

        * an invalid form element or other interactive component should be given an `aria-invalid="true"` attribute, and an `aria-describbedby="alert-id"` attribute which references the above **unique `id` attribute**

        * these attributes can be placed on a wrapping `<div role="radiogroup">` or similar element in the case of grouped elements such as radio inputs
