title: Feature Patterns
label: "Useful patterns"
status: "deprecated"
collated: false
default: "content-horizontal"
variants:
    - name: "content-horizontal"
      label: "Content (horizontal)"
      context:
          horizontal: true
          title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
          image: "http://www.fillmurray.com/315/210"
          details:
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
          action: true
    - name: "content-vertical"
      label: "Content (vertical)"
      context:
          horizontal: false
          title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
          image: "http://www.fillmurray.com/315/210"
          details:
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
          action: true
    - name: "events-horizontal"
      label: "Events (horizontal)"
      context:
          horizontal: true
          event: true
          title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
          titleLink: "#"
          image: "http://www.fillmurray.com/315/210"
          details:
            - bottom: true
              text: "Date"
            - bottom: true
              text: "Start time - end time"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
          action: false
    - name: "events-vertical"
      label: "Events (vertical)"
      context:
          horizontal: false
          title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
          titleLink: "#"
          image: "http://www.fillmurray.com/315/210"
          details:
            - bottom: true
              text: "Date"
            - bottom: true
              text: "Start time - end time"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
          action: false
    - name: "news-horizontal"
      label: "News (horizontal)"
      context:
          horizontal: true
          title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
          titleLink: "#"
          image: "http://www.fillmurray.com/315/210"
          details:
            - top: true
              links: 
                - text: "Author"
                  url: "#"
            - bottom: true
              text: "Publish date"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
          action: false
    - name: "news-vertical"
      label: "News (vertical)"
      context:
          horizontal: false
          title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
          titleLink: "#"
          image: "http://www.fillmurray.com/315/210"
          details:
            - top: true
              links: 
                - text: "Author"
                  url: "#"
            - bottom: true
              text: "Publish date"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
          action: false
