title: Breadcrumbs
status: "ready"
collated: true
context:
  ariaLabel: "Breadcrumbs"
  attributes:
    - label: "aria-label"
      value: "Breadcrumb"
  items:
    - text: Home
      link: "#"
    - text: Tier two
      link: "#"
    - text: Tier three
      attributes:
        - label: "aria-label"
          value: "Current page"
variants:
  - name: "callout"
    context:
      callout: true
      attributes:
        - label: "aria-label"
          value: "Breadcrumb call out"