title: "Layouts"
preview: '@preview-no-padding'
context:
  cards:
    -
      eyebrow: "Future"
      title: "Back to the"
      image: "https://www.fillmurray.com/800/450"
      content: "<p>Culpa nemo cum distinctio facere molestiae soluta earum reprehenderit nulla corrupti commodi, nihil, ea ut veniam laboriosam modi vero sapiente ducimus sint.</p>"
    -
      eyebrow: "Flying cars"
      title: "Spoiler alert: we don't have them yet"
      content: "<p>Some other content that shouldn't be here really.</p> <ul><li>Item one</li> <li>Item two</li></ul>"
      image: "https://www.fillmurray.com/800/450"
      meta: "<time>November 5, 2015</time>"
    -
      eyebrow: "Hoverboards"
      title: "My card title is not that long"
      image: "https://www.fillmurray.com/800/450"
      meta: "<time>November 5, 1985</time>"