title: "Layouts"
status: "wip"
preview: '@preview-no-padding'
context:
  people:
    -
      name: Braylon Owens
    -
      name: Zayden Hendricks
    -
      name: Simeon Gallegos
    -
      name: Nevaeh Valenzuela
  cards:
    -
      eyebrow: "Future"
      title: "Back to the"
      image: "https://www.fillmurray.com/800/450"
      content: "<p>Culpa nemo cum distinctio facere molestiae soluta earum reprehenderit nulla corrupti commodi, nihil, ea ut veniam laboriosam modi vero sapiente ducimus sint.</p>"
    -
      eyebrow: "Flying cars"
      title: "Spoiler alert: we don't have them yet"
      content: "<p>Some other content that shouldn't be here really.</p>"
      image: "https://www.fillmurray.com/800/450"
      meta: "<time>November 5, 2015</time>"
    -
      eyebrow: "Hoverboards"
      title: "My card title is not that long"
      image: "https://www.fillmurray.com/800/450"
      meta: "<time>November 5, 1985</time>"
    -
      eyebrow: "Lorem ipsum"
      title: "Dolor sit amet consectetur adipisicing elit"
      content: "<p>Ipsam quibusdam possimus velit, porro necessitatibus quidem consectetur atque</p>"
      image: "https://www.fillmurray.com/800/450"
      meta: "<time>October 25, 1985</time>"
    -
      title: "Quibusdam possimus velit, porro necessitatibus quidem"
      content: "<p>Esse in laudantium dolorum sequi omnis nisi?</p>"
      meta: "<time>October 25, 1985</time>"
    -
      title: "Porro necessitatibus quidem"
      content: "<p>Esse in laudantium dolorum sequi omnis nisi?</p>"
      meta: "<time>October 25, 1985</time>"