title: Buttons
status: "ready"
context:
    label: "Primary"
variants:
    - name: "success"
      context:
          type: "success"
          label: "Success"
    - name: "danger"
      context:
          type: "danger"
          label: "Danger"
    - name: "plain"
      context:
          type: "plain"
          label: "Plain"