title: Feature
label: Feature
status: "ready"
collated: true
context:
    title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
    teaser: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
variants:
    - name: "linked title"
      context:
          titlelink: "#0"
    - name: "image"
      context:
          image: "http://www.fillmurray.com/315/210"
    - name: "tag"
      context:
          tag: "optional tag"
    - name: "taglink"
      context:
          tag: "linked tag"
          taglink: "#0"
    - name: "byline"
      context:
          byline: "By Bill Murray"
    - name: "meta"
      context:
          meta: "Meta text  | Sept. 16, 2019"
    - name: "linked meta"
      context:
          meta: "Linked meta text  | Sept. 16, 2019"
          metalink: "#0"
    - name: "complete no links"
      context:
          image: "http://www.fillmurray.com/315/210"
          tag: "optional tag"
          byline: "By Bill Murray"
          meta: "Meta text  | Sept. 16, 2019"
    - name: "complete links"
      context:
          titlelink: "#0"
          image: "http://www.fillmurray.com/315/210"
          tag: "optional tag"
          taglink: "#1"
          byline: "By Bill Murray"
          meta: "Meta text  | Sept. 16, 2019"
          metalink: "#2"