title: Mods
label: "Mods"
status: "wip"
collated: false
context:
    title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
variants:
    - name: "bottom"
      context:
          details:
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
    - name: "bottom-image"
      context:
          image: "http://www.fillmurray.com/315/210"
          details:
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
    - name: "bottom-link-single"
      context:
          details:
            - bottom: true
              links:
                - text: "Related info"
                  url: "#"
    - name: "bottom-link-multi"
      context:
          details:
            - bottom: true
              links: 
                - text: "Related info"
                  url: "#"
                - text: "Feb. 20, 2020"
                  url: "#"
    - name: "bottom-multi"
      context:
          details:
            - bottom: true
              text: "Feb. 20, 2020"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
    - name: "bottom-multi-link-single"
      context:
          details:
            - bottom: true
              links:
                - text: "Feb. 20, 2020"
                  url: "#"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
    - name: "bottom-multi-link-multi"
      context:
          details:
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
            - bottom: true
              links:
                - text: "Related info"
                  url: "#"
                - text: "Feb. 20, 2020"
                  url: "#"
    - name: "image"
      context:
          image: "http://www.fillmurray.com/315/210"
    - name: "top"
      context:
          details:
            - top: true
              text: "Feb. 20, 2020"
    - name: "top-image"
      context:
          image: "http://www.fillmurray.com/315/210"
          details:
            - top: true
              text: "Feb. 20, 2020"
    - name: "top-link-single"
      context:
          details:
            - top: true
              links:
                - text: "Feb. 20, 2020"
                  url: "#"
    - name: "top-link-multi"
      context:
          details:
            - top: true
              links:
                - text: "Related info"
                  url: "#"
                - text: "Feb. 20, 2020"
                  url: "#"
    - name: "top-multi"
      context:
          details:
            - top: true
              text: "Relevant info"
            - top: true
              text: "Feb. 20, 2020"
    - name: "top-multi-link-single"
      context:
          details:
            - top: true
              links:
                - text: "Relevant info"
                  url: "#"
            - top: true
              text: "Feb. 20, 2020"
    - name: "top-multi-link-multi"
      context:
          details:
            - top: true
              text: "Ron Swanson"
            - top: true
              links:
                - text: "Relevant info"
                  url: "#"
                - text: "Feb. 20, 2020"
                  url: "#"
    - name: "mixed"
      context:
          details:
            - top: true
              text: "Relevant info"
            - bottom: true
              text: "Feb. 20, 2020"
    - name: "mixed-image"
      context:
          image: "http://www.fillmurray.com/315/210"
          details:
            - top: true
              text: "Relevant info"
            - bottom: true
              text: "Feb. 20, 2020"
    - name: "mixed-link-single"
      context:
          details:
            - top: true
              links:
                - text: "Relevant info"
                  url: "#"
            - bottom: true
              links:
                - text: "Feb. 20, 2020"
                  url: "#"
    - name: "mixed-link-multi"
      context:
          details:
            - top: true
              links:
                - text: "Relevant info"
                  url: "#"
                - text: "Relevant info"
                  url: "#"
            - bottom: true
              links:
                - text: "Ron Swanson"
                  url: "#"
                - text: "Feb. 20, 2020"
                  url: "#"
    - name: "mixed-multi"
      context:
          details:
            - top: true
              text: "Relevant info"
            - top: true
              text: "Feb. 20, 2020"
            - bottom: true
              text: "By Ron Swanson"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
    - name: "mixed-multi-link-single"
      context:
          details:
            - top: true
              links:
                - text: "Relevant info"
                  url: "#"
            - top: true
              text: "Feb. 20, 2020"
            - bottom: true
              links:
                - text: "Ron Swanson"
                  url: "#"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
    - name: "mixed-multi-link-multi"
      context:
          details:
            - top: true
              links:
                - text: "Relevant info"
                  url: "#"
                - text: "Relevant info"
                  url: "#"
            - top: true
              text: "Feb. 20, 2020"
            - bottom: true
              text: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
            - bottom: true
              links:
                - text: "Relevant info"
                  url: "#"
                - text: "Ron Swanson"
                  url: "#"
