title: "Link"
status: "ready"
collated: true
context:
    link: "#"
    text: "link text"
variants:
    - name: "bold"
      context:
          text: "bold link"
          attributes:
            - label: "class"
              value: "rvt-link-bold"
    - name: "aria-labelled"
      context:
          text: "link with aria-roles"
          attributes:
              - label: "aria-current"
                value: "page"