context:
  siteContainer: "rvt-container-lg"
  siteTitle: "Rivet Design System"
  siteSubtitle: "Indiana University"
  mainNav:
    -
      text: "Nav Item One"
      url: "#"
    - 
      text: "Nav Item Two"
      url: "#"
    - 
      text: "Nav Item Three"
      url: "#"
      current: true
      children:
        -
          text: "Sub One"
          url: "#"
        -
          text: "Sub Three"
          url: "#"
        -
          text: "Sub Three"
          url: "#"
    - 
      text: "Nav Item Four"
      url: "#"
  # Sizes
  sizes:
      - xxs
      - xs
      - sm
      - md
      - lg
      - xl
      - xxl