title: "Textarea"
status: "ready"
collated: true
context:
    id: "default"
    alert: false
variants:
    - name: "disabled"
      context:
          id: "disabled"
          modifier: "disabled"
          alert: false
    - name: "success"
      context:
          id: "success"
          class: "success"
          alert: true
          alertVariant: "\\@alert-inline--success"
    - name: "warning"
      context:
          id: "warning"
          class: "warning"
          alert: true
          alertVariant: "\\@alert-inline--warning"
    - name: "danger"
      context:
          id: "danger"
          class: "danger"
          alert: true
          alertVariant: "\\@alert-inline--danger"
    - name: "info"
      context:
          id: "info"
          class: "info"
          alert: true
          alertVariant: "\\@alert-inline"