title: 'Avatar'
status: 'ready'
collated: 'true'
context:
  text: 'XS'
  modifier: '--xs'
variants:
  - name: 'small'
    context:
      text: 'SM'
      modifier: '--sm'
  - name: 'regular'
    context:
      text: 'RG'
      modifier: false
  - name: 'medium'
    context:
      text: 'MD'
      modifier: '--md'
  - name: 'large'
    context:
      text: 'LG'
      modifier: '--lg'
  - name: 'extra-large'
    context:
      text: 'XL'
      modifier: '--xl'
  - name: 'extra-small-image'
    context:
      image: 'http://www.fillmurray.com/300/300'
      modifier: '--xs'
  - name: 'small-image'
    context:
      image: 'http://www.fillmurray.com/300/300'
      modifier: '--sm'
  - name: 'regular-image'
    context:
      image: 'http://www.fillmurray.com/300/300'
      modifier: false
  - name: 'medium-image'
    context:
      image: 'http://www.fillmurray.com/300/300'
      modifier: '--md'
  - name: 'large-image'
    context:
      image: 'http://www.fillmurray.com/300/300'
      modifier: '--lg'
  - name: 'extra-large-image'
    context:
      image: 'http://www.fillmurray.com/300/300'
      modifier: '--xl'
