title: News Feature
label: News Feature
status: "alpha"
collated: true
context:
    title: "Lorem ipsum dolor sit amet consectetur adipiscing elit"
    teaser: "Vero blanditiis eos aliquam. Magnam voluptatem delectus. Incidunt sed at sit nobis sit earum minima. Temporibus tenetur tempora hic voluptatem tenetur enim consectetur nam neque."
    image: "http://www.fillmurray.com/300/300"