title: "Utilities"
status: "ready"
context:
    flexText:
        - "One"
        - "Two"
        - "Three"
        - "Four"
        - "Five"
    spacings:
        - abbr: -xxs
          rem: .25rem
          pixels: 4
          name: Extra extra small
        - abbr: -xs
          rem: .5rem
          pixels: 8
          name: Extra small
        - abbr: -sm
          rem: 1rem
          pixels: 16
          name: Small
        - abbr: -md
          rem: 1.5rem
          pixels: 24
          name: Medium
        - abbr: -lg
          rem: 2rem
          pixels: 32
          name: Large
        - abbr: -xl
          rem: 2.5rem
          pixels: 40
          name: Extra large
        - abbr: -xxl
          rem: 3rem
          pixels: 48
          name: Extra extra large
    typeScale:
        - abbr: -xxs
          rem: .75
          pixels: 12
        - abbr: -xs
          rem: .875
          pixels: 14
        - abbr: -base
          rem: 1
          pixels: 16
        - rem: 1.125
          pixels: 18
        - abbr: -sm
          rem: 1.25
          pixels: 20
        - rem: 1.4375
          pixels: 23
        - abbr: -md
          rem: 1.625
          pixels: 26
        - rem: 1.8125
          pixels: 29
        - abbr: -lg
          rem: 2
          pixels: 32
        - rem: 2.25
          pixels: 36
        - abbr: -xl
          rem: 2.5625
          pixels: 41
        - rem: 2.875
          pixels: 46
        - abbr: -xxl
          rem: 3.25
          pixels: 52
    typeScaleText: Lorem ipsum